In [1]:
# =========================
# Importação de bibliotecas
# =========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Configuração visual
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

In [2]:
# =========================
# Carregamento dos dados
# =========================

path = "../data/raw/"

t21 = pd.read_excel(path + "Tabela 2.1 (RendCaract_Geo).xls",sheet_name="2024")
t27 = pd.read_excel(path + "Tabela 2.7 (RendInstru_caract_BR).xls",sheet_name="2024")
t213 = pd.read_excel(path + "Tabela 2.13 (Indice_Gini_Geo).xls",sheet_name="2024")
t215 = pd.read_excel(path + "Tabela 2.15 (Indice_Palma_Geo).xls",sheet_name="2024")

Limpando os dados - Primeira tabela

In [3]:
t21.head(10)

,"Tabela 2.1 - Rendimento domiciliar per capita médio e mediano, por sexo e cor ou raça, segundo as Grandes Regiões, as Unidades da Federação e os Municípios das Capitais - Brasil - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Grandes Regiões, Unidades da Federação e Munic...",Rendimento domiciliar per capita das pessoas (R$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total,NaN,Sexo,NaN,NaN,NaN,Cor ou raça,NaN,NaN,...,NaN,NaN,Sexo e cor ou raça,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Homem,NaN,Mulher,NaN,Branca,NaN,Parda,...,Preta ou parda,NaN,Homem branco,NaN,Homem preto ou pardo,NaN,Mulher branca,NaN,Mulher preta ou parda,NaN
4,NaN,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,...,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,Mediano
5,Brasil,2017.273643,1327.60392,2076.932539,1357.212439,1960.483028,1282.574571,2692.252397,1649.075634,1498.927337,...,1507.54693,1058.564457,2765.453701,1677.100585,1569.865018,1106.05453,2624.427217,1624.501778,1446.9431,1015.40086
6,Norte,1388.970777,898.586015,1411.602233,918.55177,1366.498294,874.089392,1919.493884,1148.055895,1251.389042,...,1262.427693,849.855822,1977.928935,1194.523984,1284.321378,867.906054,1866.68909,1119.372969,1240.094956,827.968847
7,Rondônia,1724.21217,1253.680586,1781.52738,1292.518614,1666.907894,1212.638382,2131.047926,1411.383763,1547.939828,...,1564.853296,1197.497799,2304.40302,1418.421493,1579.226362,1202.953314,1963.596856,1344.85759,1550.171417,1189.89437
8,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098,2563.371148,1679.671822,1675.193406,...,1702.700437,1283.753769,2826.492391,1969.638151,1697.919608,1333.364436,2295.993532,1500.931334,1707.443386,1270.097757
9,Acre,1250.463013,750.385905,1263.04795,761.950092,1237.909898,734.699356,1763.574225,1066.541087,1156.954221,...,1138.505175,712.487429,1878.357281,1098.36462,1142.981379,717.454181,1662.540831,1013.785554,1133.906251,710.823709

In [4]:
t21.info()

<class 'pandas.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 23 columns):
 #   Column                                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                                    --------------  -----
 0   Tabela 2.1 - Rendimento domiciliar per capita médio e mediano, por sexo e cor ou raça, segundo as Grandes Regiões, as Unidades da Federação e os Municípios das Capitais - Brasil - 2024  64 non-null     str
 1   Unnamed: 1                                                                                                                                                                                63 non-null     object
 2   Unnamed: 2                                                                                                                                                                                61 non-null     object
 3   Unnamed: 3                                                                                                                                                                                63 non-null     object
 4   Unnamed: 4                                                                                                                                                                                61 non-null     object
 5   Unnamed: 5                                                                                                                                                                                62 non-null     object
 6   Unnamed: 6                                                                                                                                                                                61 non-null     object
 7   Unnamed: 7                                                                                                                                                                                63 non-null     object
 8   Unnamed: 8                                                                                                                                                                                61 non-null     object
 9   Unnamed: 9                                                                                                                                                                                62 non-null     object
 10  Unnamed: 10                                                                                                                                                                               61 non-null     object
 11  Unnamed: 11                                                                                                                                                                               62 non-null     object
 12  Unnamed: 12                                                                                                                                                                               61 non-null     object
 13  Unnamed: 13                                                                                                                                                                               62 non-null     object
 14  Unnamed: 14                                                                                                                                                                               61 non-null     object
 15  Unnamed: 15                                                                                                                                                                               63 non-null     object
 16  Unnamed: 16                                                                                                                                                                               61 non-null     object
 17  Unnamed: 17                                                                                                                                                                               62 non-null     object
 18  Unnamed: 18                                                                                                                                                                               61 non-null     object
 19  Unnamed: 19                                                                                                                                                                               62 non-null     object
 20  Unnamed: 20                                                                                                                                                                               61 non-null     object
 21  Unnamed: 21                                                                                                                                                                               62 non-null     object
 22  Unnamed: 22                                                                                                                                                                               61 non-null     object
dtypes: object(22), str(1)
memory usage: 12.5+ KB

In [5]:
#Ler múltiplas linhas de cabeçalho
t21 = pd.read_excel(
    path + "Tabela 2.1 (RendCaract_Geo).xls",
    sheet_name="2024",
    header=[1,2,3,4,5]
)

In [6]:
t21.head()

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 13_level_0,Unnamed: 14_level_0,Unnamed: 15_level_0,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0,Unnamed: 22_level_0
,"Grandes Regiões, Unidades da Federação e Municípios das Capitais",Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),...,Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$),Rendimento domiciliar per capita das pessoas (R$)
,Unnamed: 0_level_2,Total,Total,Sexo,Sexo,Sexo,Sexo,Cor ou raça,Cor ou raça,Cor ou raça,...,Cor ou raça,Cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça,Sexo e cor ou raça
,Unnamed: 0_level_3,Unnamed: 1_level_3,Unnamed: 2_level_3,Homem,Homem,Mulher,Mulher,Branca,Branca,Parda,...,Preta ou parda,Preta ou parda,Homem branco,Homem branco,Homem preto ou pardo,Homem preto ou pardo,Mulher branca,Mulher branca,Mulher preta ou parda,Mulher preta ou parda
,Unnamed: 0_level_4,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,...,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,Mediano,Médio,Mediano
0,Brasil,2017.273643,1327.603920,2076.932539,1357.212439,1960.483028,1282.574571,2692.252397,1649.075634,1498.927337,...,1507.546930,1058.564457,2765.453701,1677.100585,1569.865018,1106.054530,2624.427217,1624.501778,1446.943100,1015.400860
1,Norte,1388.970777,898.586015,1411.602233,918.551770,1366.498294,874.089392,1919.493884,1148.055895,1251.389042,...,1262.427693,849.855822,1977.928935,1194.523984,1284.321378,867.906054,1866.689090,1119.372969,1240.094956,827.968847
2,Rondônia,1724.212170,1253.680586,1781.527380,1292.518614,1666.907894,1212.638382,2131.047926,1411.383763,1547.939828,...,1564.853296,1197.497799,2304.403020,1418.421493,1579.226362,1202.953314,1963.596856,1344.857590,1550.171417,1189.894370
3,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098,2563.371148,1679.671822,1675.193406,...,1702.700437,1283.753769,2826.492391,1969.638151,1697.919608,1333.364436,2295.993532,1500.931334,1707.443386,1270.097757
4,Acre,1250.463013,750.385905,1263.047950,761.950092,1237.909898,734.699356,1763.574225,1066.541087,1156.954221,...,1138.505175,712.487429,1878.357281,1098.364620,1142.981379,717.454181,1662.540831,1013.785554,1133.906251,710.823709

In [7]:
#achatando as colunas 
t21.columns = [
    "_".join([str(i) for i in col if "Unnamed" not in str(i)])
    for col in t21.columns
]
t21.head(10)

,"Grandes Regiões, Unidades da Federação e Municípios das Capitais",Rendimento domiciliar per capita das pessoas (R$)_Total_Médio,Rendimento domiciliar per capita das pessoas (R$)_Total_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Sexo_Homem_Médio,Rendimento domiciliar per capita das pessoas (R$)_Sexo_Homem_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Sexo_Mulher_Médio,Rendimento domiciliar per capita das pessoas (R$)_Sexo_Mulher_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Cor ou raça _Branca_Médio,Rendimento domiciliar per capita das pessoas (R$)_Cor ou raça _Branca_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Cor ou raça _Parda_Médio,...,Rendimento domiciliar per capita das pessoas (R$)_Cor ou raça _Preta ou parda_Médio,Rendimento domiciliar per capita das pessoas (R$)_Cor ou raça _Preta ou parda_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Homem branco_Médio,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Homem branco_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Homem preto ou pardo_Médio,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Homem preto ou pardo_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Mulher branca_Médio,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Mulher branca_Mediano,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Mulher preta ou parda_Médio,Rendimento domiciliar per capita das pessoas (R$)_Sexo e cor ou raça_Mulher preta ou parda_Mediano
0,Brasil,2017.273643,1327.603920,2076.932539,1357.212439,1960.483028,1282.574571,2692.252397,1649.075634,1498.927337,...,1507.546930,1058.564457,2765.453701,1677.100585,1569.865018,1106.054530,2624.427217,1624.501778,1446.943100,1015.400860
1,Norte,1388.970777,898.586015,1411.602233,918.551770,1366.498294,874.089392,1919.493884,1148.055895,1251.389042,...,1262.427693,849.855822,1977.928935,1194.523984,1284.321378,867.906054,1866.689090,1119.372969,1240.094956,827.968847
2,Rondônia,1724.212170,1253.680586,1781.527380,1292.518614,1666.907894,1212.638382,2131.047926,1411.383763,1547.939828,...,1564.853296,1197.497799,2304.403020,1418.421493,1579.226362,1202.953314,1963.596856,1344.857590,1550.171417,1189.894370
3,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098,2563.371148,1679.671822,1675.193406,...,1702.700437,1283.753769,2826.492391,1969.638151,1697.919608,1333.364436,2295.993532,1500.931334,1707.443386,1270.097757
4,Acre,1250.463013,750.385905,1263.047950,761.950092,1237.909898,734.699356,1763.574225,1066.541087,1156.954221,...,1138.505175,712.487429,1878.357281,1098.364620,1142.981379,717.454181,1662.540831,1013.785554,1133.906251,710.823709
5,Rio Branco,1541.371157,939.710445,1578.085454,957.770383,1508.009724,910.579543,2249.044684,1389.819612,1368.422846,...,1348.846974,856.987473,2379.089406,1397.800160,1365.654331,868.157609,2133.925889,1311.014156,1333.488432,844.922195
6,Amazonas,1237.071322,813.773098,1254.542074,827.613838,1219.778601,797.587698,1732.239752,1019.456670,1140.658092,...,1152.223411,788.896860,1758.686820,1002.577682,1179.823489,810.703109,1710.217832,1027.781268,1123.785049,761.658537
7,Manaus,1501.646840,948.936898,1541.830252,984.995119,1464.159417,936.451920,2031.632700,1175.739674,1351.427421,...,1363.637402,912.417354,2116.455180,1154.013848,1407.821775,943.282986,1965.148289,1180.822645,1320.281376,868.095409
8,Roraima,1530.864451,878.798552,1558.527750,931.594984,1503.738274,840.151621,2055.938403,1041.040907,1353.002947,...,1397.947770,843.722997,1934.915108,1064.849280,1484.973832,923.515769,2163.102538,1003.968398,1310.583185,811.503880
9,Boa Vista,1644.393140,943.865678,1672.937752,975.885967,1617.307835,931.600816,2181.047328,1098.112365,1432.261375,...,1484.417991,939.126577,2069.659002,1144.624568,1570.562087,951.742663,2278.670035,1040.825710,1401.291080,926.236178

In [8]:
#renomeando as colunas

t21 = t21.rename(columns={
    t21.columns[0]: "regiao",
    t21.columns[1]: "renda_media",
    t21.columns[2]: "renda_mediana",
    t21.columns[3]: "renda_media_homem",
    t21.columns[4]: "renda_mediana_homem",
    t21.columns[5]: "renda_media_mulher",
    t21.columns[6]: "renda_mediana_mulher"
})
#chamando somente colunas validas
t21 = t21[[
    "regiao",
    "renda_media",
    "renda_mediana",
    "renda_media_homem",
    "renda_mediana_homem",
    "renda_media_mulher",
    "renda_mediana_mulher"
]]
t21.head(10)

,regiao,renda_media,renda_mediana,renda_media_homem,renda_mediana_homem,renda_media_mulher,renda_mediana_mulher
0,Brasil,2017.273643,1327.603920,2076.932539,1357.212439,1960.483028,1282.574571
1,Norte,1388.970777,898.586015,1411.602233,918.551770,1366.498294,874.089392
2,Rondônia,1724.212170,1253.680586,1781.527380,1292.518614,1666.907894,1212.638382
3,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098
4,Acre,1250.463013,750.385905,1263.047950,761.950092,1237.909898,734.699356
5,Rio Branco,1541.371157,939.710445,1578.085454,957.770383,1508.009724,910.579543
6,Amazonas,1237.071322,813.773098,1254.542074,827.613838,1219.778601,797.587698
7,Manaus,1501.646840,948.936898,1541.830252,984.995119,1464.159417,936.451920
8,Roraima,1530.864451,878.798552,1558.527750,931.594984,1503.738274,840.151621
9,Boa Vista,1644.393140,943.865678,1672.937752,975.885967,1617.307835,931.600816

In [9]:
# limpado até o limite dos dados
t21 = t21.iloc[:60] 
# resetando indice
t21 = t21.reset_index(drop=True)

# convertendo para números
cols = [
    "renda_media",
    "renda_mediana",
    "renda_media_homem",
    "renda_mediana_homem",
    "renda_media_mulher",
    "renda_mediana_mulher"
]

t21[cols] = t21[cols].apply(pd.to_numeric, errors="coerce")
t21.head()

,regiao,renda_media,renda_mediana,renda_media_homem,renda_mediana_homem,renda_media_mulher,renda_mediana_mulher
0,Brasil,2017.273643,1327.603920,2076.932539,1357.212439,1960.483028,1282.574571
1,Norte,1388.970777,898.586015,1411.602233,918.551770,1366.498294,874.089392
2,Rondônia,1724.212170,1253.680586,1781.527380,1292.518614,1666.907894,1212.638382
3,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098
4,Acre,1250.463013,750.385905,1263.047950,761.950092,1237.909898,734.699356

In [10]:
t21.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   regiao                60 non-null     str
 1   renda_media           60 non-null     float64
 2   renda_mediana         60 non-null     float64
 3   renda_media_homem     60 non-null     float64
 4   renda_mediana_homem   60 non-null     float64
 5   renda_media_mulher    60 non-null     float64
 6   renda_mediana_mulher  60 non-null     float64
dtypes: float64(6), str(1)
memory usage: 3.4 KB

Tratar tabela t27

In [11]:
t27.head(10)

,"Tabela 2.7 - Rendimento domiciliar per capita médio e mediano, por sexo e cor ou raça, segundo o nível de instrução - Brasil - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nível de instrução (1),Rendimento domiciliar per capita (R$),NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total,Sexo,NaN,Cor ou raça,NaN,NaN,NaN
3,NaN,NaN,Homem,Mulher,Branca,Parda,Preta,Preta ou parda
4,Rendimento médio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Total,2017.273643,2076.932539,1960.483028,2692.252397,1498.927337,1544.723021,1507.54693
6,Sem instrução ou fundamental incompleto,1345.98755,1361.883514,1329.518796,1645.868629,1178.219363,1203.853713,1183.319674
7,Ensino fundamental completo ou médio incompleto,1473.492413,1557.585824,1385.207794,1868.39235,1229.457809,1278.224087,1239.103211
8,Ensino médio completo ou superior incompleto,1921.076193,2084.71243,1771.147846,2344.318754,1606.747833,1613.812021,1608.202767
9,Ensino superior completo,4725.729885,5273.916493,4333.640594,5407.369512,3597.119356,3518.909744,3581.430408

In [12]:
#Ler múltiplas linhas de cabeçalho
t27 = pd.read_excel(
    path + "Tabela 2.7 (RendInstru_caract_BR).xls",
    sheet_name="2024",
    header=[1,2,3,4,5]
)
t27.head(20)

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0
,Nível de instrução (1),Rendimento domiciliar per capita (R$),Rendimento domiciliar per capita (R$),Rendimento domiciliar per capita (R$),Rendimento domiciliar per capita (R$),Rendimento domiciliar per capita (R$),Rendimento domiciliar per capita (R$),Rendimento domiciliar per capita (R$)
,Unnamed: 0_level_2,Total,Sexo,Sexo,Cor ou raça,Cor ou raça,Cor ou raça,Cor ou raça
,Unnamed: 0_level_3,Unnamed: 1_level_3,Homem,Mulher,Branca,Parda,Preta,Preta ou parda
,Rendimento médio,Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4,Unnamed: 6_level_4,Unnamed: 7_level_4
0,Total,2017.273643,2076.932539,1960.483028,2692.252397,1498.927337,1544.723021,1507.546930
1,Sem instrução ou fundamental incompleto,1345.987550,1361.883514,1329.518796,1645.868629,1178.219363,1203.853713,1183.319674
2,Ensino fundamental completo ou médio incompleto,1473.492413,1557.585824,1385.207794,1868.392350,1229.457809,1278.224087,1239.103211
3,Ensino médio completo ou superior incompleto,1921.076193,2084.712430,1771.147846,2344.318754,1606.747833,1613.812021,1608.202767
4,Ensino superior completo,4725.729885,5273.916493,4333.640594,5407.369512,3597.119356,3518.909744,3581.430408
5,Rendimento mediano,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Total,1327.603920,1357.212439,1282.574571,1649.075634,1038.102935,1139.922324,1058.564457
7,Sem instrução ou fundamental incompleto,1136.847470,1140.290062,1132.024550,1406.392321,985.948949,1047.169041,996.818738
8,Ensino fundamental completo ou médio incompleto,1092.166122,1179.671059,1006.067494,1396.808709,941.509069,1033.661206,956.902870
9,Ensino médio completo ou superior incompleto,1423.266422,1540.735557,1332.845671,1718.520107,1232.596812,1278.253626,1244.613145
10,Ensino superior completo,3214.480428,3523.346442,2991.646591,3720.697892,2489.263663,2542.198824,2494.087804
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Notas: Exclusive as pessoas cuja condição no a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Rendimentos deflacionados para reais médios de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,(1) Exclusive pessoas com menos de 15 anos de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#Achatando as colunas 
t27.columns = [
    "_".join([str(i) for i in col if "Unnamed" not in str(i)])
    for col in t27.columns
]
t27.head(10)


#renomeando as colunas

t27 = t27.rename(columns={
    t27.columns[0]: "escolaridade",
    t27.columns[1]: "renda_",
    t27.columns[2]: "renda_homem",
    t27.columns[3]: "renda_mulher"
})

#chamando somente colunas validas
t27 = t27[[
"escolaridade",
"renda_",
"renda_homem",
"renda_mulher"
]]

t27.head()

,escolaridade,renda_,renda_homem,renda_mulher
0,Total,2017.273643,2076.932539,1960.483028
1,Sem instrução ou fundamental incompleto,1345.987550,1361.883514,1329.518796
2,Ensino fundamental completo ou médio incompleto,1473.492413,1557.585824,1385.207794
3,Ensino médio completo ou superior incompleto,1921.076193,2084.712430,1771.147846
4,Ensino superior completo,4725.729885,5273.916493,4333.640594

In [14]:
#Separando os datasets
t27_media = t27.iloc[0:5].copy()
t27_media = t27_media.rename(columns={
    t27_media.columns[0]: "escolaridade",
    t27_media.columns[1]: "renda_media",
    t27_media.columns[2]: "renda_media_homem",
    t27_media.columns[3]: "renda_media_mulher"
})
t27_mediana = t27.iloc[6:11].copy()
t27_mediana = t27_mediana.rename(columns={
    t27_mediana.columns[0]: "escolaridade",
    t27_mediana.columns[1]: "renda_mediana",
    t27_mediana.columns[2]: "renda_mediana_homem",
    t27_mediana.columns[3]: "renda_mediana_mulher"
})
t27_media.head()

,escolaridade,renda_media,renda_media_homem,renda_media_mulher
0,Total,2017.273643,2076.932539,1960.483028
1,Sem instrução ou fundamental incompleto,1345.987550,1361.883514,1329.518796
2,Ensino fundamental completo ou médio incompleto,1473.492413,1557.585824,1385.207794
3,Ensino médio completo ou superior incompleto,1921.076193,2084.712430,1771.147846
4,Ensino superior completo,4725.729885,5273.916493,4333.640594

In [15]:
t27_mediana.head()

,escolaridade,renda_mediana,renda_mediana_homem,renda_mediana_mulher
6,Total,1327.603920,1357.212439,1282.574571
7,Sem instrução ou fundamental incompleto,1136.847470,1140.290062,1132.024550
8,Ensino fundamental completo ou médio incompleto,1092.166122,1179.671059,1006.067494
9,Ensino médio completo ou superior incompleto,1423.266422,1540.735557,1332.845671
10,Ensino superior completo,3214.480428,3523.346442,2991.646591

In [16]:
#unir as tabelas
t27 = pd.merge(
    t27_media,
    t27_mediana,
    on="escolaridade",
    how="left"
)

In [17]:
t27.head()

,escolaridade,renda_media,renda_media_homem,renda_media_mulher,renda_mediana,renda_mediana_homem,renda_mediana_mulher
0,Total,2017.273643,2076.932539,1960.483028,1327.603920,1357.212439,1282.574571
1,Sem instrução ou fundamental incompleto,1345.987550,1361.883514,1329.518796,1136.847470,1140.290062,1132.024550
2,Ensino fundamental completo ou médio incompleto,1473.492413,1557.585824,1385.207794,1092.166122,1179.671059,1006.067494
3,Ensino médio completo ou superior incompleto,1921.076193,2084.712430,1771.147846,1423.266422,1540.735557,1332.845671
4,Ensino superior completo,4725.729885,5273.916493,4333.640594,3214.480428,3523.346442,2991.646591

## Tratar tabela t213

In [18]:
t213.head(20)

,"Tabela 2.13 - Índice de Gini da distribuição do rendimento domiciliar per capita, segundo as Grandes Regiões, as Unidades da Federação e os Municípios das Capitais - Brasil - 2024",Unnamed: 1
0,NaN,NaN
1,NaN,NaN
2,NaN,NaN
3,"Grandes Regiões, Unidades da Federação e Munic...",Índice de Gini
4,NaN,NaN
5,NaN,NaN
6,Brasil,0.504405
7,Norte,0.487887
8,Rondônia,0.441574
9,Porto Velho,0.452601
10,Acre,0.502353
11,Rio Branco,0.51559
12,Amazonas,0.474152
13,Manaus,0.479858
14,Roraima,0.529671
15,Boa Vista,0.536514
16,Pará,0.490423
17,Belém,0.525641
18,Amapá,0.509397
19,Macapá,0.520823

In [19]:
#Ler múltiplas linhas de cabeçalho
t213 = pd.read_excel(
    path + "Tabela 2.13 (Indice_Gini_Geo).xls",
    sheet_name="2024",
    header=[1,2,3,4,5,6]
)

t213.head()

,Unnamed: 0_level_0,Unnamed: 1_level_0
,Unnamed: 0_level_1,Unnamed: 1_level_1
,Unnamed: 0_level_2,Unnamed: 1_level_2
,"Grandes Regiões, Unidades da Federação e Municípios das Capitais",Índice de Gini
,Unnamed: 0_level_4,Unnamed: 1_level_4
,Unnamed: 0_level_5,Unnamed: 1_level_5
0,Brasil,0.504405
1,Norte,0.487887
2,Rondônia,0.441574
3,Porto Velho,0.452601
4,Acre,0.502353

In [20]:
#achatando as colunas 
t213.columns = [
    "_".join([str(i) for i in col if "Unnamed" not in str(i)])
    for col in t213.columns
]
t213.head(10)

,"Grandes Regiões, Unidades da Federação e Municípios das Capitais",Índice de Gini
0,Brasil,0.504405
1,Norte,0.487887
2,Rondônia,0.441574
3,Porto Velho,0.452601
4,Acre,0.502353
5,Rio Branco,0.515590
6,Amazonas,0.474152
7,Manaus,0.479858
8,Roraima,0.529671
9,Boa Vista,0.536514

In [21]:
t213.tail(20)

,"Grandes Regiões, Unidades da Federação e Municípios das Capitais",Índice de Gini
44,Sul,0.456877
45,Paraná,0.473285
46,Curitiba,0.508919
47,Santa Catarina,0.429901
48,Florianópolis,0.489008
49,Rio Grande do Sul,0.458147
50,Porto Alegre,0.521255
51,Centro-Oeste,0.484514
52,Mato Grosso do Sul,0.454251
53,Campo Grande,0.475165
54,Mato Grosso,0.441923
55,Cuiabá,0.510311
56,Goiás,0.461940
57,Goiânia,0.478818
58,Distrito Federal,0.546515
59,Brasília,0.546515
60,NaN,NaN
61,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN
62,Notas: Rendimentos deflacionados para reais mé...,NaN
63,Exclusive as pessoas cuja condição no arranjo ...,NaN

In [ ]:
# limpado até o limite dos dados
t213 = t213.iloc[:60] 
# resetando indice
t213 = t213.reset_index(drop=True)

t213.tail()

,"Grandes Regiões, Unidades da Federação e Municípios das Capitais",Índice de Gini
55,Cuiabá,0.510311
56,Goiás,0.461940
57,Goiânia,0.478818
58,Distrito Federal,0.546515
59,Brasília,0.546515

In [23]:
#renomeando as colunas

t213 = t213.rename(columns={
    t213.columns[0]: "regiao",
    t213.columns[1]: "indice_gini"
})

t213.head()

        regiao  indice_gini
0       Brasil     0.504405
1        Norte     0.487887
2     Rondônia     0.441574
3  Porto Velho     0.452601
4         Acre     0.502353

## Tratar tabela 2.15

In [24]:
t215.head(20)

,"Tabela 2.15 - Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento, e Índice de Palma, segundo as Grandes Regiões, as Unidades da Federação e os Municípios das Capitais - Brasil - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,"Grandes Regiões, Unidades da Federação e Munic...",Distribuição do rendimento domiciliar per capi...,NaN,NaN,Índice de Palma\n(C/A)
4,NaN,NaN,NaN,NaN,NaN
5,NaN,Até 40% (A),Mais de 40% a 90% (B),Mais de 90% (C),NaN
6,NaN,NaN,NaN,NaN,NaN
7,Brasil,11.961451,48.44456,39.593988,3.310133
8,Norte,12.799865,48.880445,38.31969,2.993757
9,Rondônia,14.87755,50.585118,34.537332,2.321439
10,Porto Velho,13.846504,51.522422,34.631074,2.50107
11,Acre,11.879139,49.635162,38.485698,3.239772
12,Rio Branco,11.235597,49.056913,39.707491,3.534079
13,Amazonas,13.504124,49.038171,37.457704,2.773797
14,Manaus,13.458625,48.97275,37.568625,2.791416
15,Roraima,11.068387,47.535507,41.396105,3.74003
16,Boa Vista,10.30631,48.842794,40.850896,3.963678
17,Pará,12.823453,48.24556,38.930986,3.035921
18,Belém,11.35583,46.767101,41.87707,3.687716
19,Amapá,12.075248,47.227039,40.697713,3.370342

In [27]:
#Ler múltiplas linhas de cabeçalho
t215 = pd.read_excel(
    path + "Tabela 2.15 (Indice_Palma_Geo).xls",
    sheet_name="2024",
    header=[1,2,3,4,5,6,7]
)

t215.head()

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1
,Unnamed: 0_level_2,Unnamed: 1_level_2,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2
,"Grandes Regiões, Unidades da Federação e Municípios das Capitais","Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento (%)","Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento (%)","Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento (%)",Índice de Palma\n(C/A)
,Unnamed: 0_level_4,Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4
,Unnamed: 0_level_5,Até 40% (A),Mais de 40% a 90% (B),Mais de 90% (C),Unnamed: 4_level_5
,Unnamed: 0_level_6,Unnamed: 1_level_6,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6
0,Brasil,11.961451,48.444560,39.593988,3.310133
1,Norte,12.799865,48.880445,38.319690,2.993757
2,Rondônia,14.877550,50.585118,34.537332,2.321439
3,Porto Velho,13.846504,51.522422,34.631074,2.501070
4,Acre,11.879139,49.635162,38.485698,3.239772

In [28]:
#achatando as colunas 
t215.columns = [
    "_".join([str(i) for i in col if "Unnamed" not in str(i)])
    for col in t215.columns
]
t215.head(10)

,"Grandes Regiões, Unidades da Federação e Municípios das Capitais","Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento (%)_Até 40% (A)","Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento (%)_Mais de 40% a 90% (B)","Distribuição do rendimento domiciliar per capita, por classes de percentual de pessoas em ordem crescente de rendimento (%)_Mais de 90% (C)",Índice de Palma\n(C/A)
0,Brasil,11.961451,48.444560,39.593988,3.310133
1,Norte,12.799865,48.880445,38.319690,2.993757
2,Rondônia,14.877550,50.585118,34.537332,2.321439
3,Porto Velho,13.846504,51.522422,34.631074,2.501070
4,Acre,11.879139,49.635162,38.485698,3.239772
5,Rio Branco,11.235597,49.056913,39.707491,3.534079
6,Amazonas,13.504124,49.038171,37.457704,2.773797
7,Manaus,13.458625,48.972750,37.568625,2.791416
8,Roraima,11.068387,47.535507,41.396105,3.740030
9,Boa Vista,10.306310,48.842794,40.850896,3.963678

In [29]:
#renomeando as colunas

t215 = t215.rename(columns={
    t215.columns[0]: "regiao",
    t215.columns[1]: "renda_40pobres",
    t215.columns[2]: "renda_50meio",
    t215.columns[3]: "renda_10ricos",
    t215.columns[4]: "indice_palma"     
})

t215.head()

        regiao  renda_40pobres  renda_50meio  renda_10ricos  indice_palma
0       Brasil       11.961451     48.444560      39.593988      3.310133
1        Norte       12.799865     48.880445      38.319690      2.993757
2     Rondônia       14.877550     50.585118      34.537332      2.321439
3  Porto Velho       13.846504     51.522422      34.631074      2.501070
4         Acre       11.879139     49.635162      38.485698      3.239772

In [30]:
t215.tail(20)

,regiao,renda_40pobres,renda_50meio,renda_10ricos,indice_palma
44,Sul,14.372222,49.623269,36.004509,2.505146
45,Paraná,13.687528,48.890637,37.421835,2.734010
46,Curitiba,11.357205,50.224642,38.418152,3.382712
47,Santa Catarina,15.640598,50.359185,34.000217,2.173844
48,Florianópolis,11.577667,52.464300,35.958033,3.105810
49,Rio Grande do Sul,13.939604,49.799186,36.261210,2.601309
50,Porto Alegre,10.548750,50.788229,38.663021,3.665176
51,Centro-Oeste,13.093689,48.625841,38.280470,2.923582
52,Mato Grosso do Sul,14.090590,50.826260,35.083150,2.489828
53,Campo Grande,12.971741,50.753746,36.274513,2.796426
54,Mato Grosso,14.840974,50.382487,34.776539,2.343279
55,Cuiabá,11.939611,48.880168,39.180221,3.281532
56,Goiás,14.160972,49.097058,36.741971,2.594594
57,Goiânia,13.378569,49.390215,37.231216,2.782900
58,Distrito Federal,9.578061,49.448088,40.973851,4.277886
59,Brasília,9.578061,49.448088,40.973851,4.277886
60,NaN,NaN,NaN,NaN,NaN
61,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN
62,Notas: Exclusive as pessoas cuja condição no a...,NaN,NaN,NaN,NaN
63,Rendimentos deflacionados para reais médios do...,NaN,NaN,NaN,NaN

In [31]:

# limpado até o limite dos dados
t215 = t215.iloc[:60] 
# resetando indice
t215 = t215.reset_index(drop=True)

t215.tail()

,regiao,renda_40pobres,renda_50meio,renda_10ricos,indice_palma
55,Cuiabá,11.939611,48.880168,39.180221,3.281532
56,Goiás,14.160972,49.097058,36.741971,2.594594
57,Goiânia,13.378569,49.390215,37.231216,2.782900
58,Distrito Federal,9.578061,49.448088,40.973851,4.277886
59,Brasília,9.578061,49.448088,40.973851,4.277886

## Juntando as 3 tabelas de região

In [34]:
#unir as tabelas
regiao_features = pd.merge(
    t21,
    t213,
    on="regiao",
    how="left"
)
regiao_features.head()

,regiao,renda_media,renda_mediana,renda_media_homem,renda_mediana_homem,renda_media_mulher,renda_mediana_mulher,indice_gini
0,Brasil,2017.273643,1327.603920,2076.932539,1357.212439,1960.483028,1282.574571,0.504405
1,Norte,1388.970777,898.586015,1411.602233,918.551770,1366.498294,874.089392,0.487887
2,Rondônia,1724.212170,1253.680586,1781.527380,1292.518614,1666.907894,1212.638382,0.441574
3,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098,0.452601
4,Acre,1250.463013,750.385905,1263.047950,761.950092,1237.909898,734.699356,0.502353

In [35]:
#unir as tabelas
regiao_features = pd.merge(
    regiao_features,
    t215,
    on="regiao",
    how="left"
)
regiao_features.head()

,regiao,renda_media,renda_mediana,renda_media_homem,renda_mediana_homem,renda_media_mulher,renda_mediana_mulher,indice_gini,renda_40pobres,renda_50meio,renda_10ricos,indice_palma
0,Brasil,2017.273643,1327.603920,2076.932539,1357.212439,1960.483028,1282.574571,0.504405,11.961451,48.444560,39.593988,3.310133
1,Norte,1388.970777,898.586015,1411.602233,918.551770,1366.498294,874.089392,0.487887,12.799865,48.880445,38.319690,2.993757
2,Rondônia,1724.212170,1253.680586,1781.527380,1292.518614,1666.907894,1212.638382,0.441574,14.877550,50.585118,34.537332,2.321439
3,Porto Velho,1881.521419,1375.848747,1938.015771,1411.072293,1825.445706,1322.711098,0.452601,13.846504,51.522422,34.631074,2.501070
4,Acre,1250.463013,750.385905,1263.047950,761.950092,1237.909898,734.699356,0.502353,11.879139,49.635162,38.485698,3.239772

In [36]:
#extraindo bases
regiao_features.to_excel("regiao_features.xlsx", index=False)
t27.to_excel("t27.xlsx", index=False)