In [4]:
# =========================
# Importação de bibliotecas
# =========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Configuração visual
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

In [5]:
# =========================
# Carregamento dos dados
# =========================

path = "../data/raw/"

t21 = pd.ExcelFile(path + "Tabela 2.1 (RendCaract_Geo).xls")
t27 = pd.ExcelFile(path + "Tabela 2.7 (RendInstru_caract_BR).xls")
t213 = pd.ExcelFile(path + "Tabela 2.13 (Indice_Gini_Geo).xls")
t215 = pd.ExcelFile(path + "Tabela 2.15 (Indice_Palma_Geo).xls")

anos = ['2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024']

In [6]:
estados = [
"Rondônia","Acre","Amazonas","Roraima","Pará","Amapá","Tocantins",
"Maranhão","Piauí","Ceará","Rio Grande do Norte","Paraíba","Pernambuco",
"Alagoas","Sergipe","Bahia",
"Minas Gerais","Espírito Santo","Rio de Janeiro","São Paulo",
"Paraná","Santa Catarina","Rio Grande do Sul",
"Mato Grosso do Sul","Mato Grosso","Goiás","Distrito Federal"
]

def classificar_nivel(df, coluna_local):

    nivel = []
    ultimo_estado = None

    for lugar in df[coluna_local]:

        if lugar in estados and lugar != ultimo_estado:
            nivel.append("estado")
            ultimo_estado = lugar

        elif lugar == ultimo_estado:
            nivel.append("capital")

        else:
            nivel.append("outro")

    df["nivel"] = nivel
    return df

In [7]:


lista_regioes = []

for ano in anos:
    t21 = pd.read_excel(
    path + "Tabela 2.1 (RendCaract_Geo).xls",
    sheet_name=ano,
    header=[1,2,3,4,5]
    )
    #achatando as colunas 
    t21.columns = [
        "_".join([str(i) for i in col if "Unnamed" not in str(i)])
        for col in t21.columns
    ]
    
       
    t21 = t21.rename(columns={
        t21.columns[0]: "regiao",
        t21.columns[1]: "renda_media",
        t21.columns[2]: "renda_mediana",
        t21.columns[3]: "renda_media_homem",
        t21.columns[4]: "renda_mediana_homem",
        t21.columns[5]: "renda_media_mulher",
        t21.columns[6]: "renda_mediana_mulher"
    })
    #chamando somente colunas validas
    t21 = t21[[
        "regiao",
        "renda_media",
        "renda_mediana",
        "renda_media_homem",
        "renda_mediana_homem",
        "renda_media_mulher",
        "renda_mediana_mulher"
    ]]

    # limpado até o limite dos dados
    t21 = t21.iloc[:60] 
    # resetando indice
    t21 = t21.reset_index(drop=True)

    # convertendo para números
    cols = [
        "renda_media",
        "renda_mediana",
        "renda_media_homem",
        "renda_mediana_homem",
        "renda_media_mulher",
        "renda_mediana_mulher"
    ]

    t21[cols] = t21[cols].apply(pd.to_numeric, errors="coerce")
    #retirar cidades
    t21 = classificar_nivel(t21, "regiao")
    t21 = t21[t21["nivel"] == "estado"]
    # adicionar coluna ano
    t21["ano"] = int(ano)

    lista_regioes.append(t21)

t21_final = pd.concat(lista_regioes, ignore_index=True)
t21_final

,regiao,renda_media,renda_mediana,renda_media_homem,renda_mediana_homem,renda_media_mulher,renda_mediana_mulher,nivel,ano
0,Rondônia,1300.691705,855.302663,1333.910328,864.725720,1267.192880,844.892933,estado,2012
1,Acre,1169.906683,628.226058,1209.028099,633.719493,1132.284390,620.829461,estado,2012
2,Amazonas,1230.260223,626.321963,1248.473284,627.008373,1211.898928,625.941401,estado,2012
3,Roraima,1521.296107,858.233352,1523.641684,866.600322,1518.953067,851.127688,estado,2012
4,Pará,1044.137547,615.499311,1056.273232,615.359981,1032.280917,615.871658,estado,2012
...,...,...,...,...,...,...,...,...,...
346,Rio Grande do Sul,2525.893226,1692.084388,2583.139739,1738.640495,2471.518116,1653.552550,estado,2024
347,Mato Grosso do Sul,2113.998931,1439.803207,2152.735375,1480.992349,2077.359370,1423.419178,estado,2024
348,Mato Grosso,2245.138158,1608.111783,2322.234385,1662.765023,2169.912815,1552.307061,estado,2024
349,Goiás,2050.597075,1401.912261,2136.806338,1424.358976,1966.515277,1370.358588,estado,2024
350,Distrito Federal,3280.983008,1787.597320,3391.896263,1904.711247,3178.266725,1700.032792,estado,2024

In [8]:


lista_regioes = []

for ano in anos:
    t213 = pd.read_excel(
    path + "Tabela 2.13 (Indice_Gini_Geo).xls",
    sheet_name=ano,
    header=[1,2,3,4,5,6]
    )
    #achatando as colunas 
    t213.columns = [
        "_".join([str(i) for i in col if "Unnamed" not in str(i)])
        for col in t213.columns
    ]
    
       
    t213 = t213.rename(columns={
    t213.columns[0]: "regiao",
    t213.columns[1]: "indice_gini"
    })

    # limpado até o limite dos dados
    t213 = t213.iloc[:60] 
    # resetando indice
    t213 = t213.reset_index(drop=True)

    #retirar cidades
    t213 = classificar_nivel(t213, "regiao")
    t213 = t213[t213["nivel"] == "estado"]
    # adicionar coluna ano
    t213["ano"] = int(ano)

    lista_regioes.append(t213)

t213_final = pd.concat(lista_regioes, ignore_index=True)
t213_final

                 regiao  indice_gini   nivel   ano
0              Rondônia     0.487644  estado  2012
1                  Acre     0.566313  estado  2012
2              Amazonas     0.589507  estado  2012
3               Roraima     0.549460  estado  2012
4                  Pará     0.533561  estado  2012
..                  ...          ...     ...   ...
346   Rio Grande do Sul     0.458147  estado  2024
347  Mato Grosso do Sul     0.454251  estado  2024
348         Mato Grosso     0.441923  estado  2024
349               Goiás     0.461940  estado  2024
350    Distrito Federal     0.546515  estado  2024

[351 rows x 4 columns]

In [9]:


lista_regioes = []

for ano in anos:
    t215 = pd.read_excel(
    path + "Tabela 2.15 (Indice_Palma_Geo).xls",
    sheet_name=ano,
    header=[1,2,3,4,5,6,7]
    )
    #achatando as colunas 
    t215.columns = [
        "_".join([str(i) for i in col if "Unnamed" not in str(i)])
        for col in t215.columns
    ]
    
     #renomeando as colunas

    t215 = t215.rename(columns={
        t215.columns[0]: "regiao",
        t215.columns[1]: "renda_40pobres",
        t215.columns[2]: "renda_50meio",
        t215.columns[3]: "renda_10ricos",
        t215.columns[4]: "indice_palma"     
    })

    # limpado até o limite dos dados
    t215 = t215.iloc[:60] 
    # resetando indice
    t215 = t215.reset_index(drop=True)

    #retirar cidades
    t215 = classificar_nivel(t215, "regiao")
    t215 = t215[t215["nivel"] == "estado"]
    # adicionar coluna ano
    t215["ano"] = int(ano)

    lista_regioes.append(t215)

t215_final = pd.concat(lista_regioes, ignore_index=True)
t215_final

,regiao,renda_40pobres,renda_50meio,renda_10ricos,indice_palma,nivel,ano
0,Rondônia,12.326267,50.128746,37.544987,3.045933,estado,2012
1,Acre,9.236823,46.819619,43.943558,4.757432,estado,2012
2,Amazonas,9.150662,41.701004,49.148334,5.371014,estado,2012
3,Roraima,10.073250,46.481071,43.445679,4.312975,estado,2012
4,Pará,10.723300,47.295831,41.980869,3.914921,estado,2012
...,...,...,...,...,...,...,...
346,Rio Grande do Sul,13.939604,49.799186,36.261210,2.601309,estado,2024
347,Mato Grosso do Sul,14.090590,50.826260,35.083150,2.489828,estado,2024
348,Mato Grosso,14.840974,50.382487,34.776539,2.343279,estado,2024
349,Goiás,14.160972,49.097058,36.741971,2.594594,estado,2024
350,Distrito Federal,9.578061,49.448088,40.973851,4.277886,estado,2024

In [10]:
desigualdade_regioes = t21_final.merge(t213_final, on=["regiao","ano"])
desigualdade_regioes = desigualdade_regioes.merge(t215_final, on=["regiao","ano"])
desigualdade_regioes

,regiao,renda_media,renda_mediana,renda_media_homem,renda_mediana_homem,renda_media_mulher,renda_mediana_mulher,nivel_x,ano,indice_gini,nivel_y,renda_40pobres,renda_50meio,renda_10ricos,indice_palma,nivel
0,Rondônia,1300.691705,855.302663,1333.910328,864.725720,1267.192880,844.892933,estado,2012,0.487644,estado,12.326267,50.128746,37.544987,3.045933,estado
1,Acre,1169.906683,628.226058,1209.028099,633.719493,1132.284390,620.829461,estado,2012,0.566313,estado,9.236823,46.819619,43.943558,4.757432,estado
2,Amazonas,1230.260223,626.321963,1248.473284,627.008373,1211.898928,625.941401,estado,2012,0.589507,estado,9.150662,41.701004,49.148334,5.371014,estado
3,Roraima,1521.296107,858.233352,1523.641684,866.600322,1518.953067,851.127688,estado,2012,0.549460,estado,10.073250,46.481071,43.445679,4.312975,estado
4,Pará,1044.137547,615.499311,1056.273232,615.359981,1032.280917,615.871658,estado,2012,0.533561,estado,10.723300,47.295831,41.980869,3.914921,estado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Rio Grande do Sul,2525.893226,1692.084388,2583.139739,1738.640495,2471.518116,1653.552550,estado,2024,0.458147,estado,13.939604,49.799186,36.261210,2.601309,estado
347,Mato Grosso do Sul,2113.998931,1439.803207,2152.735375,1480.992349,2077.359370,1423.419178,estado,2024,0.454251,estado,14.090590,50.826260,35.083150,2.489828,estado
348,Mato Grosso,2245.138158,1608.111783,2322.234385,1662.765023,2169.912815,1552.307061,estado,2024,0.441923,estado,14.840974,50.382487,34.776539,2.343279,estado
349,Goiás,2050.597075,1401.912261,2136.806338,1424.358976,1966.515277,1370.358588,estado,2024,0.461940,estado,14.160972,49.097058,36.741971,2.594594,estado
350,Distrito Federal,3280.983008,1787.597320,3391.896263,1904.711247,3178.266725,1700.032792,estado,2024,0.546515,estado,9.578061,49.448088,40.973851,4.277886,estado

In [11]:


lista_regioes = []

for ano in anos:



        t27 = pd.read_excel(
            path + "Tabela 2.7 (RendInstru_caract_BR).xls",
            sheet_name=ano,
            header=[1,2,3,4,5]
        )
        #Achatando as colunas 
        t27.columns = [
            "_".join([str(i) for i in col if "Unnamed" not in str(i)])
            for col in t27.columns
        ]
        #renomeando as colunas
        t27 = t27.rename(columns={
            t27.columns[0]: "escolaridade",
            t27.columns[1]: "renda_",
            t27.columns[2]: "renda_homem",
            t27.columns[3]: "renda_mulher"
        })

        #achamando somente colunas validas
        t27 = t27[[
        "escolaridade",
        "renda_",
        "renda_homem",
        "renda_mulher"
        ]]

        #Separando os datasets
        t27_media = t27.iloc[0:5].copy()
        t27_media = t27_media.rename(columns={
            t27_media.columns[0]: "escolaridade",
            t27_media.columns[1]: "renda_media",
            t27_media.columns[2]: "renda_media_homem",
            t27_media.columns[3]: "renda_media_mulher"
        })
        t27_mediana = t27.iloc[6:11].copy()
        t27_mediana = t27_mediana.rename(columns={
            t27_mediana.columns[0]: "escolaridade",
            t27_mediana.columns[1]: "renda_mediana",
            t27_mediana.columns[2]: "renda_mediana_homem",
            t27_mediana.columns[3]: "renda_mediana_mulher"
        })

        #unir as tabelas
        t27 = pd.merge(
            t27_media,
            t27_mediana,
            on="escolaridade",
            how="left"
        )

        # adicionar coluna ano
        t27["ano"] = int(ano)

        lista_regioes.append(t27)

t27_final = pd.concat(lista_regioes, ignore_index=True)
t27_final

,escolaridade,renda_media,renda_media_homem,renda_media_mulher,renda_mediana,renda_mediana_homem,renda_mediana_mulher,ano
0,Total,1697.131909,1720.477441,1674.772937,1006.875314,1018.682579,994.835874,2012
1,Sem instrução ou fundamental incompleto,1117.447518,1112.571801,1122.368262,839.577424,840.279000,838.838220,2012
2,Ensino fundamental completo ou médio incompleto,1365.710582,1439.004115,1293.200283,972.014420,1041.860863,901.171108,2012
3,Ensino médio completo ou superior incompleto,2023.579365,2161.832642,1901.438032,1412.102831,1525.736710,1311.296217,2012
4,Ensino superior completo,5469.392172,6090.339458,5023.085763,3536.391587,3986.448495,3280.499500,2012
...,...,...,...,...,...,...,...,...
60,Total,2017.273643,2076.932539,1960.483028,1327.603920,1357.212439,1282.574571,2024
61,Sem instrução ou fundamental incompleto,1345.987550,1361.883514,1329.518796,1136.847470,1140.290062,1132.024550,2024
62,Ensino fundamental completo ou médio incompleto,1473.492413,1557.585824,1385.207794,1092.166122,1179.671059,1006.067494,2024
63,Ensino médio completo ou superior incompleto,1921.076193,2084.712430,1771.147846,1423.266422,1540.735557,1332.845671,2024
64,Ensino superior completo,4725.729885,5273.916493,4333.640594,3214.480428,3523.346442,2991.646591,2024

In [12]:
t27_final.to_excel("escolaridade_renda_brasil.xlsx", index=False)
desigualdade_regioes.to_excel("desigualdade_regioes_2012_2024.xlsx", index=False)